### ISSUE TITLE
Encrypted document modification is not supported Trace:\\n#0 \/var\/www\/owncloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255)

### ISSUE THREAD

**Issue by enoch85** [owncloud/search_lucene#45]
Found a new bug debugging another one: https://github.com/owncloud/core/issues/12240#issuecomment-63388646
### Steps to reproduce

Don´t know. 
### Expected behaviour

No errors
### Actual behaviour

I get this in owncloud.log:

``` json
{"app":"search_lucene","message":"Encrypted document modification is not supported Trace:\\n#0 \/var\/www\/owncloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.6?%?????...', NULL)\n#1 \/var\/www\/owncloud\/apps\/search_lucene\/document\/Pdf.php(21): Zend_Pdf::parse('%PDF-1.6?%?????...')\n#2 \/var\/www\/owncloud\/apps\/search_lucene\/document\/Pdf.php(69): OCA\\Search_Lucene\\Document\\Pdf->__construct('%PDF-1.6?%?????...', false, false)\n#3 \/var\/www\/owncloud\/apps\/search_lucene\/lib\/indexer.php(94): OCA\\Search_Lucene\\Document\\Pdf::loadPdf('%PDF-1.6?%?????...')\n#4 \/var\/www\/owncloud\/apps\/search_lucene\/lib\/hooks.php(79): OCA\\Search_Lucene\\Indexer::indexFile('\/Testresultat P...', 'enoch')\n#5 [internal function]: OCA\\Search_Lucene\\Hooks::doIndexFile('{\"path\":\"\\\/Test...')\n#6 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/legacy\/queuedjob.php(17): call_user_func(Array, '{\"path\":\"\\\/Test...')\n#7 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(36): OC\\BackgroundJob\\Legacy\\QueuedJob->run(Array)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/queuedjob.php(27): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#9 \/var\/www\/owncloud\/cron.php(126): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 {main}","level":3,"time":"2014-11-17T22:28:13+00:00"}
```
### Server configuration

Ubuntu Server 12.04

**Database:**
Server version: 5.5.38-0ubuntu0.12.04.1 (Ubuntu)
**PHP version:**
PHP 5.3.10-1ubuntu3.15 with Suhosin-Patch (cli) (built: Oct 29 2014 12:19:04)
**ownCloud version:** (see ownCloud admin page)
7.0.3
**Updated from an older ownCloud or fresh install:**
Updated from stable 5 and then later stable 6
**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
External Storage Support
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer
ownCloud SMS
Music

**The content of config/config.php:**

``` php
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'example.se',
#  'dbhost' => 'localhost.localdomain',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'check_for_working_webdav' => false,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'example.se',
    1 => 'www.example.se',
  ),
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'appstoreenabled' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
No
### Client configuration

**Browser:**
Version 37.0.2062.120 m
**Operating system:**
Windows 8.1
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
{"app":"search_lucene","message":"Encrypted document modification is not supported Trace:\\n#0 \/var\/www\/owncloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.6?%?????...', NULL)\n#1 \/var\/www\/owncloud\/apps\/search_lucene\/document\/Pdf.php(21): Zend_Pdf::parse('%PDF-1.6?%?????...')\n#2 \/var\/www\/owncloud\/apps\/search_lucene\/document\/Pdf.php(69): OCA\\Search_Lucene\\Document\\Pdf->__construct('%PDF-1.6?%?????...', false, false)\n#3 \/var\/www\/owncloud\/apps\/search_lucene\/lib\/indexer.php(94): OCA\\Search_Lucene\\Document\\Pdf::loadPdf('%PDF-1.6?%?????...')\n#4 \/var\/www\/owncloud\/apps\/search_lucene\/lib\/hooks.php(79): OCA\\Search_Lucene\\Indexer::indexFile('\/Testresultat P...', 'enoch')\n#5 [internal function]: OCA\\Search_Lucene\\Hooks::doIndexFile('{\"path\":\"\\\/Test...')\n#6 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/legacy\/queuedjob.php(17): call_user_func(Array, '{\"path\":\"\\\/Test...')\n#7 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(36): OC\\BackgroundJob\\Legacy\\QueuedJob->run(Array)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/queuedjob.php(27): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#9 \/var\/www\/owncloud\/cron.php(126): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 {main}","level":3,"time":"2014-11-17T22:28:13+00:00"}
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by VicDeo** [comment]
@enoch85 Are you on OC7.x still?

**Comment by enoch85** [comment]
@VicDeo Nope, 8.0.2

**Comment by VicDeo** [comment]
@enoch85 is this still reproducible with 8.0.2?

**Comment by enoch85** [comment]
@Videco Sorry, I don't know as I don't check the logs as I did in 7 anymore. And also, I turned off search lucene as it's manily log outputs anyway.

**Comment by VicDeo** [comment]
Encrypted PDF is not supported indeed. So the message is decent.
The only issue I see is a log level. There is no need to log this as an error.

**Comment by VicDeo** [comment]
`stable7`-specific
