### ISSUE TITLE
PostgreSQL error with ownCloud 8.0

### ISSUE THREAD

**Issue by buxit** [owncloud/search_lucene#69]
since upgrading to owncloud 8.0 i have the following problem with search_lucene (usinge postgresql as bacend):

```log
An exception occurred while executing 'SELECT lastval()':
SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR: lastval is not yet defined in this session

Trace:
#0 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): DoctrineDBALDriverAbstractPostgreSQLDriver->convertException('An exception oc...', Object(DoctrineDBALDriverPDOException))
#1 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(838): DoctrineDBALDBALException::driverExceptionDuringQuery(Object(DoctrineDBALDriverPDOPgSqlDriver), Object(DoctrineDBALDriverPDOException), 'SELECT lastval(...', Array)
#2 /usr/share/webapps/owncloud/lib/private/db/connection.php(111): DoctrineDBALConnection->executeQuery('SELECT lastval(...', Array, Array, NULL)
#3 /usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(541): OCDBConnection->executeQuery('SELECT lastval(...', Array, Array)
#4 /usr/share/webapps/owncloud/lib/private/db/adapterpgsql.php(14): DoctrineDBALConnection->fetchColumn('SELECT lastval(...')
#5 /usr/share/webapps/owncloud/lib/private/db/connection.php(149): OCDBAdapterPgSql->lastInsertId('oc_lucene_statu...')
#6 /usr/share/webapps/owncloud/lib/private/appframework/db/db.php(67): OCDBConnection->lastInsertId('*PREFIX*lucene_...')
#7 /usr/share/webapps/owncloud/apps/search_lucene/db/statusmapper.php(79): OCAppFrameworkDbDb->getInsertId('*PREFIX*lucene_...')
#8 /usr/share/webapps/owncloud/apps/search_lucene/db/statusmapper.php(202): OCASearch_LuceneDbStatusMapper->insert(Object(OCASearch_LuceneDbStatus))
#9 /usr/share/webapps/owncloud/apps/search_lucene/lucene/indexer.php(95): OCASearch_LuceneDbStatusMapper->getOrCreateFromFileId(4381)
#10 /usr/share/webapps/owncloud/apps/search_lucene/controller/apicontroller.php(68): OCASearch_LuceneLuceneIndexer->indexFiles(Array, Object(OC_EventSource))
#11 [internal function]: OCASearch_LuceneControllerApiController->index(NULL)
#12 /usr/share/webapps/owncloud/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
#13 /usr/share/webapps/owncloud/lib/private/appframework/http/dispatcher.php(86): OCAppFrameworkHttpDispatcher->executeController(Object(OCASearch_LuceneControllerApiController), 'index')
#14 /usr/share/webapps/owncloud/lib/private/appframework/app.php(97): OCAppFrameworkHttpDispatcher->dispatch(Object(OCASearch_LuceneControllerApiController), 'index')
#15 /usr/share/webapps/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OCAppFrameworkApp::main('ApiController', 'index', Object(OCAppFrameworkDependencyInjectionDIContainer), Array)
#16 [internal function]: OCAppFrameworkroutingRouteActionHandler->__invoke(Array)
#17 /usr/share/webapps/owncloud/lib/private/route/router.php(250): call_user_func(Object(OCAppFrameworkroutingRouteActionHandler), Array)
#18 /usr/share/webapps/owncloud/lib/base.php(763): OCRouteRouter->match('/apps/search_lu...')
#19 /usr/share/webapps/owncloud/index.php(36): OC::handleRequest()
#20 {main}","File":"/usr/share/webapps/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":91
```

**Comment by karlitschek** [comment]
@butonic any idea?

**Comment by buxit** [comment]
I have done a little research on this now:

Postgresql `lastval()` only works on sequences and the `fileid` column is not a sequence. You could make an `INSERT` query `RETURNING fileid`. 

Since `fileid` is known in php in advance you could just use this value instead:

(db/statusmapper.php:79)
```php
$entity->setFileId((int) $params[0]);
```
There is probably a cleaner way to do this.

**Comment by butonic** [comment]
@buxit https://github.com/owncloud/search_lucene/pull/73 changes the way the status is inserted. It should fix this issue as a side effect. Can you verify?

**Comment by VicDeo** [comment]
#73 is not applicable to stable8 sincz https://github.com/owncloud/core/pull/14468 is not ported there

**Comment by VicDeo** [comment]
@buxit this line is not needed at all, like  https://github.com/owncloud/search_lucene/issues/79

**Comment by VicDeo** [comment]
https://github.com/owncloud/search_lucene/pull/79 is merged
Closing as fixed in master/stable8.1/stable8
